### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by Sourc** [inda18plusplus/ggerholm-chess#3]
Implement a way in the GUI for the player to choose what a pawn should be promoted to, and execute that choice. All the functionality is there, but it has to be presented in the GUI. Does not have to be pretty.

### Todo
- [ ] Know when a pawn has to be promoted (using the board method).
- [ ] Ask the player what to promote to.
- [ ] Promote the pawn to the player's choice of piece.
